# Generated by Django 4.2.13 on 2024-07-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_facebook_social_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/cover_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/profile_pics/'),
        ),
    ]
