# Generated by Django 4.2.13 on 2024-07-22 12:06

from django.db import migrations, models
from profiles.models import TIMEZONES_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0012_alter_profile_availability_alter_profile_gigs_played_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                choices=TIMEZONES_CHOICES,
                default="UTC",
                max_length=50,
            ),
        ),
    ]
