# Generated by Django 4.2.13 on 2024-07-22 13:42

from django.db import migrations, models
from profiles.models import TIMEZONES_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_profile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commitment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----"),
                    ("just_for_fun", "Just for Fun"),
                    ("moderately_committed", "Moderately Commited"),
                    ("committed", "Committed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                choices=TIMEZONES_CHOICES,
                default="UTC",
                max_length=50,
            ),
        ),
    ]
