# Generated by Django 4.2.13 on 2024-07-23 19:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_profile_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_1',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_3',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_4',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_5',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link_6',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
