import django_filters
from django.forms import CheckboxSelectMultiple
from .models import Advertisement, AdType
from profiles.models import Genre, Skill
from dal import autocomplete
from cities_light.models import City


# Utility functions to dynamically generate choices for filters
def get_ad_type_choices():
    """
    Returns a list of tuples containing the id and name of each AdType for use in filter choices
    """
    return [(ad_type.id, ad_type.name) for ad_type in AdType.objects.all()]


def get_genre_choices():
    """
    Returns a list of tuples containing the id and name of each Genre for use in filter choices
    """
    return [(genre.id, genre.name) for genre in Genre.objects.all()]


def get_skill_choices():
    """
    Returns a list of tuples containing the id and name of each Skill for use in filter choices
    """
    return [(skill.id, skill.name) for skill in Skill.objects.all()]


class AdvertisementFilter(django_filters.FilterSet):
    """
    Filter class for Advertisement model
    """

    # CharFilter for filtering advertisements by title, using case-insensitive containment matching
    title = django_filters.CharFilter(field_name="title", lookup_expr="icontains")

    # A MultipleChoiceFilter for filtering by advertisement type
    # Choices are dynamically generated by the get_ad_type_choices function
    ad_type = django_filters.MultipleChoiceFilter(
        field_name="ad_type",
        choices=get_ad_type_choices(),
        widget=CheckboxSelectMultiple,
    )

    # A ModelChoiceFilter for filtering by location (City)
    # Uses an autocomplete widget for enhanced user experience
    location = django_filters.ModelChoiceFilter(
        queryset=City.objects.all(),
        widget=autocomplete.ModelSelect2(url="profiles:location_autocomplete"),
    )

    # A ModelMultipleChoiceFilter for filtering by genres
    # Displayed as checkboxes in the form, with custom CSS classes for layout
    genres = django_filters.ModelMultipleChoiceFilter(
        queryset=Genre.objects.all(),
        widget=CheckboxSelectMultiple(attrs={"class": "d-flex flex-wrap row-cols-4"}),
    )

    # A ModelMultipleChoiceFilter for filtering by skills
    # Displayed as checkboxes in the form, with custom CSS classes for layout
    skills = django_filters.ModelMultipleChoiceFilter(
        queryset=Skill.objects.all(),
        widget=CheckboxSelectMultiple(attrs={"class": "d-flex flex-wrap row-cols-4"}),
    )

    class Meta:
        model = Advertisement
        fields = [
            "title",
            "ad_type",
            "location",
            "genres",
            "skills",
        ]
