# Generated by Django 4.2.13 on 2024-07-17 16:14

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('openmics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmic',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='facebook_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='instagram_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='personal_website_social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='venue_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='openmic',
            name='youtube_social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
