# Generated by Django 4.2.13 on 2024-07-17 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmics', '0002_openmic_address_openmic_entry_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmic',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
