# Generated by Django 4.2.13 on 2024-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmics', '0003_alter_openmic_entry_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='entry_fee_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
